# Generated by Django 4.0.1 on 2022-03-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('edition', models.IntegerField(null=True)),
                ('bookfile', models.FileField(null=True, upload_to='')),
                ('filetype', models.CharField(max_length=20)),
                ('aname', models.CharField(max_length=20)),
                ('pname', models.CharField(max_length=20)),
            ],
        ),
    ]
