# Generated by Django 4.0.1 on 2022-03-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0002_remove_bookm_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookm',
            name='username',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
